Update Dependencies
rhunk/SnapEnhance pull request #498
Opened 2023-12-15 10:32 UTC by CanerKaraca23

2023-12-15 15:55 UTC, authorisation requested changes

2023-12-15 15:55 UTC, authorisation commented on .github/workflows/beta.yml
> +    runs-on: ubuntu-latest
Change this back.

2023-12-16 13:45 UTC, authorisation commented
Have you tested this?

2023-12-16 15:25 UTC, CanerKaraca23 commented
> Have you tested this?

Yes.

2023-12-16 15:37 UTC, authorisation approved these changes

2023-12-17 12:28 UTC, authorisation requested changes
Explanation required on why certain dependencies were downgraded

2023-12-17 13:53 UTC, CanerKaraca23 commented
> Explanation required on why certain dependencies were downgraded

Which dependencies are you talking about? None of them downgraded, you can check changed files, only tried accidently on dev branch one dependency because it's recent, i tested and failed, reverted back.

2023-12-17 13:55 UTC, authorisation approved these changes

2023-12-17 13:56 UTC, merged